[versions]
spring-boot = "4.0.2"
jspecify = "1.0.0"
jackson = "3.0.4"
junit = "6.0.2"
japicmp-plugin = "0.4.6"
jmh-plugin = "0.7.2"
spring-dependency-management-plugin = "1.1.7"
jsonrpc-starter = "0.1.0"

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
spring-web = { module = "org.springframework:spring-web" }
spring-test = { module = "org.springframework:spring-test" }
spring-webmvc = { module = "org.springframework:spring-webmvc" }
jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
micrometer-core = { module = "io.micrometer:micrometer-core" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
jsonrpc-spring-boot-starter = { module = "io.github.limehee:jsonrpc-spring-boot-starter", version.ref = "jsonrpc-starter" }

[plugins]
japicmp = { id = "me.champeau.gradle.japicmp", version.ref = "japicmp-plugin" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh-plugin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management-plugin" }
